title: Manuel Morales-Alvarado
logo: /assets/img/round_img.png
#description: A description
show_downloads: false
#theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
sass:
  style: compressed

# make sure your CSS overrides load after the theme

